# Generated by Django 4.1.4 on 2023-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_denal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=64)),
                ('c_email', models.EmailField(max_length=50)),
                ('c_subject', models.CharField(max_length=64)),
                ('c_message', models.CharField(max_length=640)),
            ],
        ),
    ]
